# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20180125_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useramount',
            name='user',
        ),
    ]
